arm_controller:
  type: position_controllers/JointTrajectoryController
  joints: 
    - arm_base_joint
    - shoulder_joint
    - bottom_wrist_joint
    - elbow_joint
    - top_wrist_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.5
    arm_base_joint:
      trajectory: 0.1
      goal: 0.1
    shoulder_joint:
      trajectory: 0.1
      goal: 0.1
    bottom_wrist_joint:
      trajectory: 0.1
      goal: 0.1
    elbow_joint:
      trajectory: 0.1
      goal: 0.1
    top_wrist_joint:
      trajectory: 0.1
      goal: 0.1
    stop_trajectory_duration: 0.5
    state_publish_rate: 25
    actions_monitor_rate: 10
  
/gazebo_ros_control:
  pid_gains:
    arm_base_joint: {p: 1000.0, i: 100.0, d: 10.0}
    shoulder_joint: {p: 1000.0, i: 100.0, d: 10.0}
    bottom_wrist_joint: {p: 1000.0, i: 100.0, d: 10.0}
    elbow_joint: {p: 1000.0, i: 100.0, d: 10.0}
    top_wrist_joint: {p: 100.0, i: 0.0, d: 0.0}
